In [4]:
import numpy as np

print("<np.empty((4,3))>\n", np.empty((4,3)))

A = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("<np.empty_like(A)>\n", np.empty_like(A))

<np.empty((4,3))>
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<np.empty_like(A)>
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
