In [1]:
import numpy as np

print("<np.ones((2,3))>\n", np.ones((2,3)))
print("<np.ones((2,3), dtype = int)>\n", np.ones((2,3), dtype = int))

A = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("<np.ones_like(A))>\n", np.ones_like(A))

<np.ones((2,3))>
 [[1. 1. 1.]
 [1. 1. 1.]]
<np.ones((2,3), dtype = int)>
 [[1 1 1]
 [1 1 1]]
<np.ones_like(A))>
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
