In [1]:
import numpy as np

x = np.array([1,5,2])
y = np.array([7,4,1])

print("<x + y>\n", x + y)
print("<x * y>\n", x * y)
print("<x - y>\n", x - y)
print("<x / y>\n", x / y)
print("<x % y>\n", x % y)

<x + y>
 [8 9 3]
<x * y>
 [ 7 20  2]
<x - y>
 [-6  1  1]
<x / y>
 [0.14285714 1.25       2.        ]
<x % y>
 [1 1 0]
