In [1]:
import numpy as np

print("<np.full((2,3), 10)>\n", np.full((2,3), 10))

print("< 10 * np.ones((2,3), dtype=int)>\n", 10 * np.ones((2,3), dtype=int))

<np.full((2,3), 10)>
 [[10 10 10]
 [10 10 10]]
< 10 * np.ones((2,3), dtype=int)>
 [[10 10 10]
 [10 10 10]]
