In [1]:
import numpy as np

a = np.zeros(3)
print("<a.ndim>\n", a.ndim)
print("<a.shape>\n", a.shape)
print("<a>\n", a)

print()

b = np.zeros((3,6))

print("<b.ndim>\n", b.ndim)
print("<b.shape>\n", b.shape)
print("<b>\n", b)


<a.ndim>
 1
<a.shape>
 (3,)
<a>
 [0. 0. 0.]

<b.ndim>
 2
<b.shape>
 (3, 6)
<b>
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
