In [1]:
import numpy as np

outcome = np.random.randint(1, 7, size = 10)

print("<outcome>\n", outcome)
print("<type(outcome)>\n", type(outcome))
print("<len(outcome)>\n", len(outcome))
print("<np.random.randint(2, size=10)>\n", np.random.randint(2, size=10))
print("<np.random.randint(1, size=10)>\n", np.random.randint(1, size=10))
print("<np.random.randint(5, size=(2,4))>\n", np.random.randint(5, size=(2,4)))

<outcome>
 [5 5 5 2 3 3 4 3 2 6]
<type(outcome)>
 <class 'numpy.ndarray'>
<len(outcome)>
 10
<np.random.randint(2, size=10)>
 [0 1 1 0 1 1 0 0 0 0]
<np.random.randint(1, size=10)>
 [0 0 0 0 0 0 0 0 0 0]
<np.random.randint(5, size=(2,4))>
 [[1 2 4 4]
 [4 2 2 0]]
