In [1]:
import numpy as np

a = np.random.rand(3,2)

print("<a>", a)
print()

b = np.random.rand(3,3,3)
print("<b>", b)

<a> [[0.69024357 0.77487684]
 [0.44419827 0.2977924 ]
 [0.12214946 0.81678396]]

<b> [[[0.43583638 0.62803007 0.90036072]
  [0.62229997 0.46345112 0.36184321]
  [0.44086247 0.68637358 0.34890739]]

 [[0.88912642 0.028065   0.42411133]
  [0.33295076 0.90946465 0.24196362]
  [0.20447777 0.7256552  0.17239164]]

 [[0.94303798 0.07308159 0.32320798]
  [0.11739302 0.17661155 0.38011291]
  [0.85206215 0.16177279 0.02633474]]]
